### ISSUE TITLE
false alarms for high clock drift

### ISSUE THREAD

**Issue by majewsky** [sapcc/ntp_exporter#1]
The clock drift measurement works reasonably well, but some data points are so far off from the preceding and following data points that a measurement error is very likely (see screenshot below). We get a small number of false alarms in our prod systems as a result of this.

Idea for a solution: If the clock drift is unusually big (e.g. > 10 ms), take multiple measurements and submit the median value.

----

<img width="909" alt="screen shot 2017-02-01 at 11 47 06" src="https://cloud.githubusercontent.com/assets/24696/22503930/37907776-e874-11e6-9a9e-1896d2278d11.png">

**Comment by Rafouf69** [comment]
https://github.com/sapcc/ntp_exporter/blob/36c6ba6b715ccc83a7ddb5c4de24c805ae5b8906/collector.go#L176

Wouldn't it be better to get the absolute value of `measurement.clockOffset` since the NTP drift can be negative ? 

Furthermore, it could be interesting to change highDrift from a constant to a parameter like clockOffset.
https://github.com/sapcc/ntp_exporter/blob/36c6ba6b715ccc83a7ddb5c4de24c805ae5b8906/collector.go#L166
