### ISSUE TITLE
Comparion/contrast with Node Exporter's NTP collector?

### ISSUE THREAD

**Issue by JamesCropcho** [sapcc/ntp_exporter#16]
Hello:

Good day to you.

I don't know much about NTP, and I'm interested in monitoring my servers' NTP clients and my servers' time accuracy (relative to consensus/"official" time).

There are two (more?) options for a Prometheus-monitored system: yours, and Node Exporter's (https://github.com/prometheus/node_exporter/blob/master/docs/TIME.md).

Why and when might someone choose one option over the other?

Thank You,
James

**Comment by majewsky** [comment]
This code was initially forked from the node-exporter because, at some point, the node exporter said that their NTP module was deprecated. This does not seem to be the case anymore. However, their NTP module seems to be significantly different at this point: Their docu says that it is "intended for use with local NTP daemons" and it appears to require them to listen for SNTP on 127.0.0.1. Our exporter does not require that. It talks to the upstream NTP server directly and compares to the system clock.
